### ISSUE TITLE
Confusing "Docker Personal" on billing for Team subscription

### ISSUE THREAD

**Issue by avbentem** [docker/hub-feedback#2194]
## Problem description

Users who are assigned a seat in a Team subscription still see "Docker Personal" in Docker Hub.

Docker Desktop does show "TEAM TIER" though. Also, **some** limits op the page (such as "0 of **unlimited** tokens active") seem to indicate that the Team subscription is somehow known. I have not validated what limits actually apply; maybe Hub really thinks this is a personal account, not a seat in a Team.

**URL**: https://hub.docker.com/billing (also, there seems to be no other place where the correct details are shown)

**Hub Username**: avanbentem (this is NOT about my private Pro account, which is linked to this GitHub account)

## Screenshots of the issue

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/1497002/151247475-5b61c52a-8786-407a-9d96-78eb79fb8148.png">

## Task List
- [x] This is **NOT** a security issue
- [ ] ~I do **NOT** have a Docker subscription~ (I do, but I don't see how it's relevant; also this is NOT about my private Pro account)
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by avbentem** [comment]
Also, confusion commenced as, after clicking the link in the Team invite email and setting up the account following that, I was shown some Choose a Plan page. That page should not be shown when a new new account is already paid for by a seat in a Team subscription.

**Comment by avbentem** [comment]
Of course, I could deduct this is _how_ it works. But, deliberate? 🤔 I still feel that being shown all this, along with "Choose a plan" after clicking the link **from the team's invite email**, is just very bad UX for your paying customers. 🤯

(Note that this issue is half a year old. Maybe things have improved since.)

**Comment by mark-dr** [comment]
You make an excellent point - I agree that could be a clearer experience. Thanks for reporting it! I've passed it onto the relevant team here.

**Comment by jcrben** [comment]
@yavorg pretty negative first experience here trying to figure out if my license is properly being picked up or not

I'll probably have to add clarification to an internal FAQ to try to head off questions

cc: @temenuzhka-thede @ingshtrom @twelsh-aw

**Comment by jcrben** [comment]
Commenting
