### ISSUE TITLE
Docker push succeeds but image never shows up on Docker Hub

### ISSUE THREAD

**Issue by wiltonsr** [docker/hub-feedback#2199]
## Problem description

Cannot push images to DockerHub following [Docker Hub Quickstart](https://docs.docker.com/docker-hub/).
Push succeeds but I cannot see the image on my Hub account. The repository remains empty.
Maybe related to #307

`docker pull wiltonsr/test` from another machine works correctly. Only image don't appears on Docker Hub.

## `docker info` output

Docker Info:
```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., 2.2.3)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 92
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 8cqlrohju445salzvjeaduxw0
  Is Manager: true
  ClusterID: o6rwfey7vm0b8cbbkiyhav2k4
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.18.7
  Manager Addresses:
   192.168.18.7:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1407cab509ff0d96baa4f0eb6ff9980270e6e620.m
 runc version: v1.1.0-0-g067aaf85
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.16.2-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.64GiB
 Name: shenlong
 ID: RN7X:62ON:UKAJ:FBSO:BMGN:JQWL:6V66:4RZ5:4PT5:NTWC:WK4T:J2BF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: wiltonsr
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

## Debug Information
**Browser name and version**:

**URL**: https://hub.docker.com/r/wiltonsr/test

**Timetamp or time range**: America/Sao_Paulo

**Public IP**: 45.181.100.243

**Hub Username**: wiltonsr

## Screenshots of the issue (if applicable)

```bash
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: wiltonsr
Password: 
WARNING! Your password will be stored unencrypted in /home/wilton/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

[0][wilton@shenlong]/tmp/dir
$ cat Dockerfile 
FROM busybox
CMD echo "Hello world! This is my first Docker image."

[0][wilton@shenlong]/tmp/dir
$ docker build -t wiltonsr/test .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM busybox
 ---> beae173ccac6
Step 2/2 : CMD echo "Hello world! This is my first Docker image."
 ---> Using cache
 ---> a58e3edf1018
Successfully built a58e3edf1018
Successfully tagged wiltonsr/test:latest

[0][wilton@shenlong]/tmp/dir
$ docker run wiltonsr/test
Hello world! This is my first Docker image.

[0][wilton@shenlong]/tmp/dir
$ docker push -a wiltonsr/test
The push refers to repository [docker.io/wiltonsr/test]
01fd6df81c8e: Layer already exists 
latest: digest: sha256:bd3d43cff821f8075a4a5c98babd3d3d5bee2ca5273a38d0ba3bce6e302e4da9 size: 527
```

![image](https://user-images.githubusercontent.com/5395065/151863123-9bdbea2a-ad4b-42fe-9a0e-a77c1b56e539.png)

![image](https://user-images.githubusercontent.com/5395065/151863154-6b891c70-f873-431b-933b-43b94fea3cb3.png)

# Task List
- [ ] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me

**Comment by ingshtrom** [comment]
We are sorry for the inconvenience. We do have an active incident going on right now which would result in some of the issues you are experiencing. Please follow along at https://status.docker.com/.

**Comment by wiltonsr** [comment]
Hi @ingshtrom, thanks for the reply.

I will close the issue and track the status link. If persists I will reopen it.

Regards.
