### ISSUE TITLE
Ubuntu 22.04 docker images can't execute apt-get because the Docker version of DockerHub is < v.20.10.9

### ISSUE THREAD

**Issue by twobombs** [docker/hub-feedback#2235]
## Problem description
Ubuntu 22.04 docker images can't execute apt-get because the Docker version of DockerHub is < v.20.10.9

issues and fixes reported all over the place. example: 
https://stackoverflow.com/questions/71941032/why-i-cannot-run-apt-update-inside-a-fresh-ubuntu22-04

**URL**: dockerhub container image builder
https://hub.docker.com/repository/registry-1.docker.io/twobombs/deploy-nvidia-docker/builds/b6a3ca1f-da82-4043-8da0-1211cbc6a46c

AMS

**Public IP**: 140.82.112.4

**Hub Username**:
twobombs

## Error messages (on screen or in browser console)

```
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```

## Screenshots of the issue (if applicable)

# Task List
- [X] This is **NOT** a security issue
- [X] I do (**NOT**) have a Docker subscription  < I actually do
- [X] I have looked through other issues and they do **NOT** apply to me  < looked for, couldn't find 'em

**Comment by chrispatrick** [comment]
Happy to say the version of Docker has now been updated to 20.10.15, so this should fix the issue.
