### ISSUE TITLE
The issue template is confusing: why should one NOT have a Docker subscription?

### ISSUE THREAD

**Issue by avbentem** [docker/hub-feedback#2236]
## Problem description

Should one NOT have an account to create issues here? If so: where does one go? Or should one leave the task list incomplete when one does have a paid account? Aside, that `<h1>Task List</h1>` is quite huge, I feel. So it must be important to you? 🤯

```
# Task List
- [ ] ...
- [ ] I do **NOT** have a Docker subscription
- [ ] ...
```

# Task List
- [x] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me (actually I didn't look)

**Comment by ingshtrom** [comment]
You are right about the second question in the task list. It should be reworded to "I do **NOT** have a paid Docker subscription" as those customers should put in a support ticket with [support](https://hub.docker.com/support/). The point of the list is to have you, the issue submitter, think about what you are submitting to avoid tickets that are better served in other places.

In terms of the size of the list, three yes/no questions are not a large ask in the grand scheme of things. 

Maybe you are referring to the full issue template being too long. This is in response to getting a lot of incomplete requests like "Docker Hub is broken" or "my IP is blocked". These requests always result in a follow-up asking for the information in the issue template anyway, so it would be best if it can be included upfront. 

Please, keep in mind that we want to help you, but we need a certain amount of information. As you have done, many people leave out pieces of the debug information anyways. It isn't that the issue will be ignored if it isn't all set, but it helps us help you all as quickly as possible.

**Comment by avbentem** [comment]
> as those customers should put in a support ticket with [support](https://hub.docker.com/support/)

Why? As a paying customer (Pro privately, Teams through work), I disagree as I may not need support, but just want to report an issue? For which I cannot even tell if others already reported if they channel that through support? Also, I tend to not spend time reporting issues that others (and maybe even I) cannot see later on. But if you really, **really** feel support should be used, then please add that instruction?

> Aside, that `<h1>Task List</h1>` is quite huge

Here I was referring to the formatting of the header (the Markdown `# Task List` of course being rendered as `<h1>`, whereas the `## Problem description` is just an `<h2>`), not to the length of the (short) task list. 🤓 

> <img width="274" alt="screenshot" title="HUGE TASK LIST RENDERING EVEN FEELS A BIT LIKE SHOUTING TO ME" src="https://user-images.githubusercontent.com/1497002/170687145-e3fcd01d-5a0b-4106-b03d-be25af4778ca.png">

**Comment by ingshtrom** [comment]
> Here I was referring to the formatting of the header 

O.o haha. Yeah, a typo for sure. Definitely not worth being that large. I will say that not many people actually follow the template so it is probably futile to have. 🤔 We can clean it up to be a bit more friendly to newcomers and not so uncompromising.

> Why? As a paying customer (Pro privately, Teams through work), I disagree as I may not need support, but just want to report an issue? For which I cannot even tell if others already reported if they channel that through support? Also, I tend to not spend time reporting issues that others (and maybe even I) cannot see later on. But if you really, really feel support should be used, then please add that instruction?

I see where you are coming from. That makes sense and I hadn't quite thought of it that way. I think it is a bias of mine due to the types of issues I tend to look at rather than looking at the whole repository of issues more objectively. I'll put in the PR next week to clean up the issue_template a bit. 

Thank you for the feedback!
