### ISSUE TITLE
No recovery code was found.

### ISSUE THREAD

**Issue by khoa-io** [docker/hub-feedback#2306]
## Problem description

2FA was successfully activated but I can't get the recovery code or generate a new one.
After entered my password, it said "No recovery code was found."

## `docker info` output

Docker Info:
```yaml

```

## Debug Information
**Browser name and version**:

**URL**: https://hub.docker.com/settings/security

**Timetamp or time range**: GMT+7 10:00

**Public IP**: 

**Hub Username**: khoa10

## Screenshots of the issue (if applicable)

# Task List
- [ ] This is **NOT** a security issue
- [X] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by Arthur-Matta** [comment]
HI. I'm having the same issue. Any updates on this matter?

**Comment by vdamery** [comment]
Closing this one due to inactivity.

Feel free to reopen it.
