### ISSUE TITLE
Can't enable 2FA with complex password (non-Latin1 characters)

### ISSUE THREAD

**Issue by Destroy666x** [docker/hub-feedback#2326]
## Problem description
Enabling 2FA doesn't work on account(s) with password that's not liked by `btoa` JS function (why is that function used there? noone knows). So the password contains non-Latin1 character(s). It happens for around a year now, even though support replied back when I first reported it that it'll get fixed and didn'tbother redirecting me here.

## `docker info` output
-

## Debug Information
**Browser name and version**: any, but e.g. latest Chrome

**URL**: https://hub.docker.com/settings/security

**Timetamp or time range**:  13:41, CEST

**Public IP**:  doesn't matter

**Hub Username**: destroy666

## Error messages (on screen or in browser console)
```
Warning: An unhandled error was caught from submitForm() DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at https://d36jcksde1wxzq.cloudfront.net/main.979f28bab293d5b9ed06.js:205:359701
    at s.use (https://d36jcksde1wxzq.cloudfront.net/main.979f28bab293d5b9ed06.js:205:1081342)
    at k (https://d36jcksde1wxzq.cloudfront.net/main.979f28bab293d5b9ed06.js:205:237038)
    at n.<computed> (https://d36jcksde1wxzq.cloudfront.net/main.979f28bab293d5b9ed06.js:205:977886)
    at https://d36jcksde1wxzq.cloudfront.net/5087.bf7796b8d1844f206d51.js:1:49374
    at Object.onClick (https://d36jcksde1wxzq.cloudfront.net/5087.bf7796b8d1844f206d51.js:1:49542)
    at onSubmit (https://d36jcksde1wxzq.cloudfront.net/5087.bf7796b8d1844f206d51.js:1:44401)
    at https://d36jcksde1wxzq.cloudfront.net/9299.9aeffb1ede45560fb865.js:1:16707
    at https://d36jcksde1wxzq.cloudfront.net/9299.9aeffb1ede45560fb865.js:1:19567
    at https://d36jcksde1wxzq.cloudfront.net/9299.9aeffb1ede45560fb865.js:1:15990
```

## Screenshots of the issue (if applicable)
-

# Task List
- [x] This is **NOT** a security issue (well, in a sense it is...)
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me
